### ISSUE TITLE
Select a value when possible values for an EnumProperty change

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/dialogos#19]
In the PocketSphinx Settings dialog, the set of possible values for the "models" property can change dynamically, when a new model is installed. Currently the new model is entered correctly into the combobox for the property, but no item is selected. Instead, an item should be selected (ideally, the same one as before). However, even when we call setValue on the property, this change is not propagated to the combobox. Fix that.

**Comment by alexanderkoller** [comment]
Sometimes I get this exception:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: value out of range
        at com.clt.properties.EnumProperty.setValue(EnumProperty.java:100)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Settings$2.done(Settings.java:166)
        at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:737)
```

**Comment by alexanderkoller** [comment]
It works correctly in the Settings in com.clt.lego. Maybe the same thing can be done for the Sphinx settings too.
