### ISSUE TITLE
FileDialog: JavaFX on Linux does not work the way it used to.

### ISSUE THREAD

**Issue by timobaumann** [coli-saar/dialogos#79]
when trying to open a file:
```
java.lang.NoClassDefFoundError: javafx/stage/DirectoryChooser
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2432)
        at java.desktop/java.awt.Component.isCoalesceEventsOverriden(Component.java:6274)
        at java.desktop/java.awt.Component.access$400(Component.java:185)
        at java.desktop/java.awt.Component$3.run(Component.java:6228)
        at java.desktop/java.awt.Component$3.run(Component.java:6226)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Component.checkCoalescing(Component.java:6225)
        at java.desktop/java.awt.Component.<init>(Component.java:6194)
        at java.desktop/java.awt.Container.<init>(Container.java:294)
        at java.desktop/javax.swing.JComponent.<init>(JComponent.java:598)
        at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:347)
        at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:325)
        at li.flor.nativejfilechooser.NativeJFileChooser.<init>(NativeJFileChooser.java:96)
        at com.clt.gui.FileChooser.standardGetFile(FileChooser.java:124)
        at com.clt.gui.FileChooser.standardGetFile(FileChooser.java:79)
        at com.clt.diamant.Main.openDocument(Main.java:306)
        at com.clt.diamant.Main.doCommand(Main.java:586)
        at com.clt.diamant.Main$4.run(Main.java:170)
        at com.clt.util.AbstractAction.actionPerformed(AbstractAction.java:141)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6354)
        at java.desktop/java.awt.Container.processEvent(Container.java:2261)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.stage.DirectoryChooser
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 57 more
```
This could be java version (happens with 1.8 and 1.11 but I don't know what I used to use) or something else.

First sub-goal: make fall-back to standard file dialog more robust to avoid error.
second sub-goal: make this work again (make sure javafx is on the class path, no idea why it's not anymore)

**Comment by alexanderkoller** [comment]
JavaFX is no longer distributed with Java: https://www.infoworld.com/article/3261066/java/javafx-will-be-removed-from-the-java-jdk.html

We may be able to pull it into the DialogOS binary via Gradle. But it seems a bit risky to mix JavaFX with Swing anyway, no?

Can we revert to the old version of the filechooser - at least for Milestone 2.0? What was wrong with it? I never had a problem.

**Comment by timobaumann** [comment]
the Java stock file chooser looks horrible on Linux. The solution I found works via JavaFX (which has beautiful file choosers across OSes). 

It turns out I had messed too much with my java setup. It does work with Java 8, but it will probably not work with Java 11 in the future anymore. So, we will eventually have to find a better solution to this.
